# ml/src/config.yaml
image_size: 256
batch_size: 16
learning_rate: 0.0003
num_epochs: 40
early_stopping_patience: 8
model_name: efficientnet_b3
weight_decay: 0.0001
label_smoothing: 0.1
device: cuda
class_names:
  - Bud Root Dropping
  - Bud Rot
  - Caterpillars
  - DryingofLeaflets
  - Flaccidity
  - Gray Leaf Spot
  - Healthy_Leaves
  - Leaf Rot
  - Leaflets
  - Yellowing
