# ml/src/config.yaml
image_size: 224
batch_size: 16
learning_rate: 0.0001
num_epochs: 15
model_name: resnet50
device: cuda
class_names:
  - Bud Root Dropping
  - Bud Rot
  - Caterpillars
  - Drying of Leaflets
  - Flaccidity
  - Gray Leaf Spot
  - Healthy Leaves
  - Leaf Rot
  - Leaflets
  - Yellowing

  
